export const styles = {
  authContainer: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    minHeight: '100vh',
    width: '100%',
    background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    margin: 0,
    padding: '1rem',
  },
  authCard: {
    backgroundColor: 'rgba(31, 41, 55, 0.95)',
    backdropFilter: 'blur(10px)',
    padding: '2.5rem',
    borderRadius: '1.5rem',
    boxShadow: '0 25px 50px -12px rgba(0, 0, 0, 0.5)',
    width: '100%',
    maxWidth: '420px',
    border: '1px solid rgba(255, 255, 255, 0.1)',
  },
  authTitle: {
    fontSize: '2rem',
    fontWeight: 'bold',
    color: '#ffffff',
    marginBottom: '2rem',
    textAlign: 'center',
    letterSpacing: '-0.5px',
  },
  form: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1.25rem',
  },
  input: {
    padding: '0.875rem 1rem',
    borderRadius: '0.75rem',
    border: '2px solid transparent',
    backgroundColor: 'rgba(17, 24, 39, 0.8)',
    color: '#ffffff',
    fontSize: '1rem',
    transition: 'all 0.2s ease',
    outline: 'none',
  },
  button: {
    padding: '0.875rem',
    borderRadius: '0.75rem',
    border: 'none',
    background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    color: '#ffffff',
    fontSize: '1rem',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'all 0.3s ease',
    boxShadow: '0 4px 15px rgba(102, 126, 234, 0.4)',
    transform: 'translateY(0)',
  },
  genderContainer: {
    display: 'flex',
    gap: '1.5rem',
    justifyContent: 'center',
    padding: '0.5rem 0',
  },
  genderLabel: {
    color: '#e5e7eb',
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    cursor: 'pointer',
    fontSize: '0.95rem',
  },
  switchText: {
    color: '#9ca3af',
    textAlign: 'center',
    marginTop: '1.5rem',
    fontSize: '0.95rem',
  },
  link: {
    color: '#818cf8',
    cursor: 'pointer',
    textDecoration: 'none',
    fontWeight: '500',
    transition: 'color 0.2s ease',
  },
  homeContainer: {
    display: 'flex',
    height: '100vh',
    width: '100%',
    backgroundColor: '#0f172a',
    margin: 0,
    padding: 0,
  },
  sidebar: {
    width: '340px',
    minWidth: '340px',
    backgroundColor: '#1e293b',
    borderRight: '1px solid rgba(100, 116, 139, 0.2)',
    display: 'flex',
    flexDirection: 'column',
    boxShadow: '2px 0 10px rgba(0, 0, 0, 0.1)',
  },
  sidebarHeader: {
    padding: '1.5rem',
    borderBottom: '1px solid rgba(100, 116, 139, 0.2)',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    background: 'linear-gradient(135deg, rgba(102, 126, 234, 0.1) 0%, rgba(118, 75, 162, 0.1) 100%)',
  },
  sidebarTitle: {
    color: '#ffffff',
    fontSize: '1.5rem',
    fontWeight: 'bold',
    margin: 0,
    letterSpacing: '-0.5px',
  },
  logoutButton: {
    padding: '0.625rem 1.25rem',
    borderRadius: '0.75rem',
    border: 'none',
    backgroundColor: '#dc2626',
    color: '#ffffff',
    fontSize: '0.875rem',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    boxShadow: '0 2px 8px rgba(220, 38, 38, 0.3)',
  },
  conversationsList: {
    flex: 1,
    overflowY: 'auto',
    padding: '0.5rem 0',
  },
  conversation: {
    display: 'flex',
    alignItems: 'center',
    padding: '1rem 1.25rem',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    gap: '1rem',
    margin: '0.25rem 0.75rem',
    borderRadius: '0.75rem',
  },
  avatarContainer: {
    position: 'relative',
    flexShrink: 0,
  },
  avatar: {
    width: '52px',
    height: '52px',
    borderRadius: '50%',
    border: '3px solid rgba(100, 116, 139, 0.3)',
    transition: 'border-color 0.2s ease',
  },
  onlineBadge: {
    position: 'absolute',
    bottom: '2px',
    right: '2px',
    width: '14px',
    height: '14px',
    backgroundColor: '#10b981',
    borderRadius: '50%',
    border: '3px solid #1e293b',
    boxShadow: '0 0 10px rgba(16, 185, 129, 0.5)',
  },
  conversationInfo: {
    flex: 1,
    minWidth: 0,
  },
  conversationName: {
    color: '#f1f5f9',
    fontWeight: '600',
    margin: 0,
    fontSize: '1rem',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  messageContainer: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
    background: 'linear-gradient(180deg, #0f172a 0%, #1e293b 100%)',
  },
  messageHeader: {
    padding: '1.25rem 1.5rem',
    backgroundColor: '#1e293b',
    borderBottom: '1px solid rgba(100, 116, 139, 0.2)',
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
    boxShadow: '0 2px 10px rgba(0, 0, 0, 0.1)',
  },
  headerAvatar: {
    width: '48px',
    height: '48px',
    borderRadius: '50%',
    border: '3px solid rgba(102, 126, 234, 0.5)',
  },
  headerName: {
    color: '#ffffff',
    fontWeight: '700',
    fontSize: '1.25rem',
    margin: 0,
    letterSpacing: '-0.3px',
  },
  messagesArea: {
    flex: 1,
    overflowY: 'auto',
    padding: '1.5rem',
    display: 'flex',
    flexDirection: 'column',
    gap: '1rem',
    backgroundImage: 'radial-gradient(circle at 20% 50%, rgba(102, 126, 234, 0.03) 0%, transparent 50%), radial-gradient(circle at 80% 80%, rgba(118, 75, 162, 0.03) 0%, transparent 50%)',
  },
  messageWrapper: {
    display: 'flex',
    gap: '0.75rem',
    alignItems: 'flex-end',
    animation: 'slideIn 0.3s ease',
  },
  messageAvatar: {
    width: '36px',
    height: '36px',
    borderRadius: '50%',
    border: '2px solid rgba(100, 116, 139, 0.3)',
    flexShrink: 0,
  },
  messageBubble: {
    maxWidth: '65%',
    padding: '0.875rem 1.125rem',
    borderRadius: '1.125rem',
    boxShadow: '0 2px 8px rgba(0, 0, 0, 0.15)',
    wordWrap: 'break-word',
    transition: 'transform 0.2s ease',
  },
  messageText: {
    color: '#ffffff',
    margin: 0,
    marginBottom: '0.375rem',
    wordBreak: 'break-word',
    lineHeight: '1.5',
    fontSize: '0.95rem',
  },
  messageTime: {
    color: 'rgba(255, 255, 255, 0.6)',
    fontSize: '0.7rem',
    fontWeight: '500',
  },
  messageForm: {
    padding: '1.25rem 1.5rem',
    backgroundColor: '#1e293b',
    borderTop: '1px solid rgba(100, 116, 139, 0.2)',
    display: 'flex',
    gap: '1rem',
    alignItems: 'center',
    boxShadow: '0 -2px 10px rgba(0, 0, 0, 0.1)',
  },
  messageInput: {
    flex: 1,
    padding: '0.875rem 1.125rem',
    borderRadius: '1.5rem',
    border: '2px solid rgba(100, 116, 139, 0.3)',
    backgroundColor: '#0f172a',
    color: '#ffffff',
    fontSize: '0.95rem',
    outline: 'none',
    transition: 'all 0.2s ease',
  },
  sendButton: {
    padding: '0.875rem 1.75rem',
    borderRadius: '1.5rem',
    border: 'none',
    background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    color: '#ffffff',
    fontSize: '0.95rem',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'all 0.3s ease',
    boxShadow: '0 4px 15px rgba(102, 126, 234, 0.4)',
    minWidth: '80px',
  },
  noChat: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    color: '#64748b',
    padding: '2rem',
  },
  noChatTitle: {
    fontSize: '2.25rem',
    marginBottom: '1rem',
    fontWeight: '700',
    color: '#e2e8f0',
    letterSpacing: '-0.5px',
  },
  noChatText: {
    fontSize: '1.125rem',
    color: '#94a3b8',
    fontWeight: '400',
  },
  loadingContainer: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '3rem',
    color: '#64748b',
    fontSize: '1rem',
  },
};